// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiahccjpfidvvvnerdqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYWhjY2pwZmlkdnZ2bmVyZHFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MzIzNjEsImV4cCI6MjA1OTQwODM2MX0.ZB89z1-ZX3KIbtYHOP7X7eKiTrhOMNoHIG474KgZNC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);